# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}
      - -s -w -X main.ferretVersion={{ .Env.FERRET_VERSION }}

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

    format_overrides:
      - goos: windows
        formats: ['zip']

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - worker
    skip_push: false
    dockerfile: Dockerfile.release
    image_templates:
      - "docker.io/montferret/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "docker.io/montferret/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "docker.io/montferret/{{ .ProjectName }}:latest"
      - "ghcr.io/montferret/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/montferret/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/montferret/{{ .ProjectName }}:latest"
      - "gcr.io/montferret/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "gcr.io/montferret/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "gcr.io/montferret/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/MontFerret/{{.ProjectName}}"

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
