FROM montferret/chromium:88.0.4298.0

RUN apt-get update && apt-get install -y dumb-init ca-certificates

WORKDIR /root

# Add worker binary
COPY worker /bin/worker
EXPOSE 8080

ENTRYPOINT ["dumb-init", "--"]
CMD ["/bin/sh", "-c", "./entrypoint.sh & ./worker"]
