# Build the final container. And install
FROM microbox/chromium-headless:83.0.4103.0 as runner

RUN apt-get update && apt-get install -y dumb-init ca-certificates

WORKDIR /root

# Add worker binary
COPY worker /bin/worker
EXPOSE 8080

ENTRYPOINT ["dumb-init", "--"]
CMD ["/bin/sh", "-c", "chromium --disable-dev-shm-usage --full-memory-crash-report --no-sandbox --disable-setuid-sandbox --disable-gpu --headless --remote-debugging-port=9222 & /bin/worker"]
