name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      - name: Set up linters
        run: make install-tools

      - name: Lint
        run: |
          make lint
          make fmt
          git diff
          if [[ $(git diff) != '' ]]; then echo 'Invalid formatting!' >&2; exit 1; fi

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: |
          make compile
      - name: Test
        run: make test